import nodemailer from 'nodemailer';
import { prisma } from './prisma.js';
import { getMetrics } from './metricsService.js';
import { getAnalysisReport } from './analysisService.js';
import { monthKeyFromDate } from './receiptService.js';

const smtpConfig = {
  host: process.env.SMTP_HOST,
  port: Number(process.env.SMTP_PORT || 587),
  secure: process.env.SMTP_SECURE === 'true',
  auth: process.env.SMTP_USER
    ? {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASSWORD
      }
    : undefined
};

const transporter = nodemailer.createTransport(smtpConfig);

export async function sendMonthlyReportEmail(monthKeyInput) {
  const monthKey = monthKeyInput || monthKeyFromDate(new Date());
  const report = await getAnalysisReport(monthKey);
  const metrics = await getMetrics(monthKey);

  if (!report) {
    throw new Error(`No analysis report for ${monthKey}`);
  }

  if (!process.env.EMAIL_REPORT_TO || !process.env.EMAIL_FROM) {
    throw new Error('Email sender/recipient not configured');
  }

  const html = renderEmailTemplate({ monthKey, report, metrics });

  await transporter.sendMail({
    from: process.env.EMAIL_FROM,
    to: process.env.EMAIL_REPORT_TO,
    subject: `Receipt AI Monthly Insights – ${monthKey}`,
    html
  });

  await prisma.emailJob.upsert({
    where: { month: monthKey },
    update: {
      status: 'sent',
      sentAt: new Date()
    },
    create: {
      month: monthKey,
      status: 'sent',
      sentAt: new Date()
    }
  });
}

function renderEmailTemplate({ monthKey, report, metrics }) {
  const metricList = metrics
    .map((metric) => {
      if (metric.valueNumeric !== null && metric.valueNumeric !== undefined) {
        return `<li><strong>${metric.metricKey}</strong>: ${metric.valueNumeric} ${metric.unit || ''}</li>`;
      }
      if (metric.valueJson) {
        return `<li><strong>${metric.metricKey}</strong>: ${JSON.stringify(metric.valueJson)}</li>`;
      }
      return `<li><strong>${metric.metricKey}</strong>: n/a</li>`;
    })
    .join('');

  const recommendations = (report.recommendations || [])
    .map(
      (rec) =>
        `<li><strong>${rec.title}</strong>: ${rec.detail}<br/><em>Action:</em> ${rec.recommended_action}</li>`
    )
    .join('');

  return `
    <div style="font-family: Arial, sans-serif; color: #222;">
      <h2>Monthly Finance Review – ${monthKey}</h2>
      <p>${report.summaryText}</p>
      <h3>Key Metrics</h3>
      <ul>${metricList}</ul>
      <h3>Optimization Opportunities</h3>
      <ul>${recommendations}</ul>
      <h3>Vehicle Insights</h3>
      <pre>${JSON.stringify(report.vehicleInsights || {}, null, 2)}</pre>
      <p>Generated by Receipt AI Agent.</p>
    </div>
  `;
}

